    Program ::= PROGRAM ProgramName DeclarationList MethodDeclarationSection
                {:
                    ctx.foundSymbol(SemanticSymbol.PROGRAM_EXIT,
                        new SemanticParameters());
                :};

ProgramName ::= ID:progName
                {:
                    ctx.foundSymbol(SemanticSymbol.PROGRAM,
                        new SemanticParameters()
                        .setName(progName.toString()));
                :};